### ISSUE TITLE
Bash: Ejercicio q20

### ISSUE THREAD

**Issue by esalvarezm** [jdvelasq/courses#10]
# PROBLEMA
la pregunta planteada no es clara comparada con la respuesta esperada. Pregunta por la cantidad de tarjetas máximas de un banco y la respuesta es 1098, pero todos los bancos tienen registros por mas de 3000 tarjetas
Enviado por: Maria Claudia Ordoñez.

# EVIDENCIA
Pregunta Solicitada.
<img width="594" alt="q20" src="https://user-images.githubusercontent.com/72627651/112726035-402ac100-8ee9-11eb-8f18-0d3c60dcc2ce.png">

**Comment by hrodriguezgi-un** [comment]
Hola @esalvarezm puedes editar por fa el titulo de este issue... el error que reportas es para la q31 de bash.
Aunque está duplicado con este otro issue: https://github.com/jdvelasq/courses/issues/8

Gracias! :)
