### ISSUE TITLE
q19 bash

### ISSUE THREAD

**Issue by Daamarilesf1** [jdvelasq/courses#12]
Para realizar el ejercicio q19 de bash estoy buscando realizar un Join entre los archivos person y bank.csv. 

con esto en mente cree este código, pero no genera la unión. 

join -1 2 -2 1 -t , <(sort -t, -k2 bank.csv) <(sort -k1 person) > personbank.csv

primero organice por orden con sort ambos archivos  y luego los intento unir con join teniendo en cuenta el campo 1 SSN que es el común entre ambos.  pero definitivamente no funciona.

**Comment by Pabloc98** [comment]
Hola @Daamarilesf1, estas realizando bien el proceso sin embargo realizarlo todo en una sola linea puede ser lo que te este causando error. 

Siguiendo esta misma lógica realice el ejercicio creando un par de archivos auxiliares sorteados, que es aceptable en este caso según el monitor Carlos, para luego hacer el join sin problema; finalmente realizo el filtro con sed obteniendo el success en el ejercicio después de eliminar las comillas y seleccionar la columna en cuestión con un cut.

Te comparto la primera parte del código. 

sort -t, -k2 bank.csv > bank1.csv
sort person > person1

join -1 1 -2 2 -t, person1 bank1.csv | sed -n '/3608-2968-5750-1980/p'


Espero que sea de ayuda. 
Pablo

**Comment by lvasquezve** [comment]
@Daamarilesf1 esta solución te fue util ?
