### ISSUE TITLE
q06 bash

### ISSUE THREAD

**Issue by gcarmonap-zz** [jdvelasq/courses#13]
Hola!!!
El question 6 tiene como enunciado:
![image](https://user-images.githubusercontent.com/80118152/112769981-d7773d80-8fe9-11eb-9029-cb9980446ce7.png)

al abrir el archivo y localizar el último registro, el valor del campo Key es: 6409
![image](https://user-images.githubusercontent.com/80118152/112770074-6c7a3680-8fea-11eb-948c-62ced9a1109f.png)

el grader está arrojando el valor de la columna ccn:
![image](https://user-images.githubusercontent.com/80118152/112770088-8b78c880-8fea-11eb-9d00-cebda635230d.png)

**Comment by lvasquezve** [comment]
al parecer es un error de redacción, pero si miras detalladamente el valor que espera el grader no es del la columna `key` sino de la columna `cnn` , intenta cambiar la columna y comentas si la solución te sirve

**Comment by gcarmonap-zz** [comment]
Hola Luis

lo cambiamos y funciona, era problema de redacción, gracias
