### ISSUE TITLE
q20 bash

### ISSUE THREAD

**Issue by gcarmonap-zz** [jdvelasq/courses#14]
el enunciado del ejercicio es:
![image](https://user-images.githubusercontent.com/80118152/112770309-c4656d00-8feb-11eb-9708-f6599f787bb9.png)
al buscar en el archivo bank.csv la clave '3608-2596-5551-1068' se obtiene la key de persona: '138-25-1957':
![image](https://user-images.githubusercontent.com/80118152/112770375-28883100-8fec-11eb-81ce-63aecc85d79a.png)
y al buscar la persona '138-25-1957' en el archivo person, se obtiene el nombre:Carlene Matthews 
![image](https://user-images.githubusercontent.com/80118152/112770397-3d64c480-8fec-11eb-9bab-237dffa5e852.png)
pero cuando se ejecuta el grader, sale el nombre: Sandy Bloodworth
![image](https://user-images.githubusercontent.com/80118152/112770451-62593780-8fec-11eb-89ec-b62f53daf840.png)
está mal el valor del grader?

**Comment by lvasquezve** [comment]
El error pasa por las siguientes razones

Se busca en el archivo banck.csv el valor 3608-2596-5551-1068, el cual tiene asignado el ssn 138-25-1957. Al buscar el ssn en el archivo person el nombre asociado es Carlene Matthews 

Al buscar el resultado esperado Sandy Bloodworth en el archivo person, nos devuelve el cnn 238-51-1813Si se busca el cnn en el archivo bank.csv este no existe

Pendiente correccion del profesor
