### ISSUE TITLE
Matplotlib q1,q2,q3 graders

### ISSUE THREAD

**Issue by gcarmonap-zz** [jdvelasq/courses#15]
Al generar los graficos, de los ejercicio no se genera exactamente el gráfico en la posición del original, las dimensiones y en alguno de ellos hasta el tamaño del archivo es el mismo pero el grader no pasa.

Ejercicio 3:

generada:
![image](https://user-images.githubusercontent.com/80118152/112881567-760aa980-9091-11eb-9aa4-88c69c61514a.png)

original:
![image](https://user-images.githubusercontent.com/80118152/112881611-8589f280-9091-11eb-8b44-da067947ad85.png)

El archivo de diferencias es:
![image](https://user-images.githubusercontent.com/80118152/112881653-920e4b00-9091-11eb-9b5f-005c2b111713.png)

y el grader arroja error, la imagen generada debe ser igual? Existe alguna forma de saber el tamaño de los subplots? 

Gracias!

**Comment by jpablo146unal** [comment]
Lo más cerca que hemos estado es con la siguiente gráfica de diferencias. Curioso que algunos puntos de la gráfica superpongan perfectamente y otros no
![generada-failed-diff](https://user-images.githubusercontent.com/80066625/112926684-6adb6c00-90d9-11eb-851d-ce88b57b45c8.png)

**Comment by viviposada** [comment]
Al correr el grader de los ejercicios 1 y 2 de matplotlib se genera el error: **"grader:33: UserWarning: FixedFormatter should only be used together with FixedLocator"**
Sin embargo genera el archivo _SUCCESS, es valido entregar el ejercicio aunque se presente el mensaje?

**Comment by lvasquezve** [comment]
intestaste esta solución ?

https://stackoverflow.com/questions/63723514/userwarning-fixedformatter-should-only-be-used-together-with-fixedlocator

**Comment by jpablo146unal** [comment]
Gracias Luis, después de mucho ensayar, ya logramos sacar las 3 gráficas con SUCCESS

**Comment by lvasquezve** [comment]
Fabuloso, si tienen de pronto conocimiento que quieran dejar en este hilo, se les agradeceria mucho para las futuras generaciones

**Comment by jpablo146unal** [comment]
Las líneas más difíciles de "concretar" son las siguientes:

plt.subplots_adjust(wspace = 0.X, hspace=0.X)
axes[i].set_xlim(-X,Y) -> el i indica que en este caso se hizo con un for loop
plt.tight_layout()

Depende del gráfico solicitado se deben ajustar los valores
En los casos de scatter plot: linewidth, edgecolors, facecolors y size pueden ser relevantes

**Comment by viviposada** [comment]
> intestaste esta solución ?
> 
> https://stackoverflow.com/questions/63723514/userwarning-fixedformatter-should-only-be-used-together-with-fixedlocator

Gracias Luis, ya me funciono :)
