### ISSUE TITLE
Q13 Bash

### ISSUE THREAD

**Issue by jariasci** [jdvelasq/courses#17]
Hola, me gustaría saber por qué en este ejercicio no me arroja el success cuando pongo PYTHON3 GRADER. Si corro línea por línea del código en el Visual si funciona.
El código que uso es este:
sort -k1 -n person | sed 's/"//g' | awk 'NR == 1 {print}' | cut -d, -f3 > resultado
cat resultado

![Issue Q13 Bash](https://user-images.githubusercontent.com/80066379/114060191-bec51e00-985a-11eb-8d82-64d941a602f2.GIF)
![image](https://user-images.githubusercontent.com/80066379/114060335-e4eabe00-985a-11eb-8e6d-840001641d0b.png)

**Comment by calopezj** [comment]
Hola. Porfa borra manualmente los archivos 'resultado'$'\r' y 'fila1'$'\r'
Es posible que el grader esté intentando imprimir el primero en vez del que estas creado con los comandos.

**Comment by dizapatar** [comment]
No guardes en la variable (>resultado)
