### ISSUE TITLE
Calificación global curso - grade

### ISSUE THREAD

**Issue by ChrisWbe** [jdvelasq/courses#18]
El calificador global de curso arroja el siguiente error, impidiendo generar el archivo grade.yml para la notal final.
![Captura de pantalla de 2021-04-10 08-54-18](https://user-images.githubusercontent.com/17432129/114272163-a419b300-99da-11eb-84e4-83a485e7c182.png)

Incluso algunos ejercicios que obuvieron SUCCESS de forma individual generaron error en este punto.
![Captura de pantalla de 2021-04-10 08-58-28](https://user-images.githubusercontent.com/17432129/114272231-f4911080-99da-11eb-981b-e40faeeef6e9.png)

En otros casos se presenta errores de permisos denegados.

**Comment by JuRodUnal** [comment]
A mí también me pasa lo mismo me saca ese mismo error

**Comment by joasalazargi** [comment]
Me pasa igual, el error es el mismo de la última línea, además obtengo en el grading de cada ejercicio lo siguiente 
![image](https://user-images.githubusercontent.com/26781845/114273163-b72e8200-99de-11eb-9d48-134dbb15bada.png)

**Comment by viviposada** [comment]
> Me pasa igual, el error es el mismo de la última línea, además obtengo en el grading de cada ejercicio lo siguiente
> ![image](https://user-images.githubusercontent.com/26781845/114273163-b72e8200-99de-11eb-9d48-134dbb15bada.png)

![image](https://user-images.githubusercontent.com/80117497/114278158-164ac180-99f4-11eb-8137-92e646ca6e7a.png)

**Comment by lvasquezve** [comment]
hay varios puntos  a evaluar respecto a este tema : 

1. los que están trabajando con docker no necesitan ejecutar `python3 grade` ya que la imagen de docker viene con python 3 instalados, las personas que instalaron python3, esta haciendo procesos redundantes y generadores de errores innecesarios(me paso con varios estudiantes)

2. A los que les sale tubería rota, supongo que al ejecutar el ejercicio individualmente debe salir lo mismo, en varias sesiones se recomendó  que si los puntos de bash tienen  el comando `cut` genera incompatibilidades en el proceso 

3. a los que les genera error como `ImportError: No module named 'yaml'` se soluciona instalando

```bash
pip install pyyaml
```

**Comment by George010823** [comment]
Hola, Con python arroja el siguiente error:
![1](https://user-images.githubusercontent.com/80078715/114280091-611d0700-99fd-11eb-9842-f6b5b54fe471.JPG)
![Captura](https://user-images.githubusercontent.com/80078715/114280092-611d0700-99fd-11eb-9ed1-26f5ba48df43.JPG)

**Comment by viviposada** [comment]
> hay varios puntos a evaluar respecto a este tema :
> 
> 1. los que están trabajando con docker no necesitan ejecutar `python3 grade` ya que la imagen de docker viene con python 3 instalados, las personas que instalaron python3, esta haciendo procesos redundantes y generadores de errores innecesarios(me paso con varios estudiantes)
> 2. A los que les sale tubería rota, supongo que al ejecutar el ejercicio individualmente debe salir lo mismo, en varias sesiones se recomendó  que si los puntos de bash tienen  el comando `cut` genera incompatibilidades en el proceso
> 3. a los que les genera error como `ImportError: No module named 'yaml'` se soluciona instalando
> 
> ```shell
> pip install pyyaml
> ```

Cual es el comando correcto a usar? porque con grade solo, omitiendo el python no funciona:
![image](https://user-images.githubusercontent.com/80117497/114280109-72feaa00-99fd-11eb-8f11-9db59c9bf557.png)

**Comment by George010823** [comment]
Hola, Con python3 arroja el siguiente error: La verdad se parece mucho al de python grade solo.
![1](https://user-images.githubusercontent.com/80078715/114280259-0801a300-99fe-11eb-960b-190b37920f07.JPG)
![Captura](https://user-images.githubusercontent.com/80078715/114280261-089a3980-99fe-11eb-9044-c85a7fa96ca0.JPG)

**Comment by lvasquezve** [comment]
> > hay varios puntos a evaluar respecto a este tema :
> > 
> > 1. los que están trabajando con docker no necesitan ejecutar `python3 grade` ya que la imagen de docker viene con python 3 instalados, las personas que instalaron python3, esta haciendo procesos redundantes y generadores de errores innecesarios(me paso con varios estudiantes)
> > 2. A los que les sale tubería rota, supongo que al ejecutar el ejercicio individualmente debe salir lo mismo, en varias sesiones se recomendó  que si los puntos de bash tienen  el comando `cut` genera incompatibilidades en el proceso
> > 3. a los que les genera error como `ImportError: No module named 'yaml'` se soluciona instalando
> > 
> > ```shell
> > pip install pyyaml
> > ```
> 
> Cual es el comando correcto a usar? porque con grade solo, omitiendo el python no funciona:
> ![image](https://user-images.githubusercontent.com/80117497/114280109-72feaa00-99fd-11eb-8f11-9db59c9bf557.png)

`python grade`

**Comment by viviposada** [comment]
> > > hay varios puntos a evaluar respecto a este tema :
> > > 
> > > 1. los que están trabajando con docker no necesitan ejecutar `python3 grade` ya que la imagen de docker viene con python 3 instalados, las personas que instalaron python3, esta haciendo procesos redundantes y generadores de errores innecesarios(me paso con varios estudiantes)
> > > 2. A los que les sale tubería rota, supongo que al ejecutar el ejercicio individualmente debe salir lo mismo, en varias sesiones se recomendó  que si los puntos de bash tienen  el comando `cut` genera incompatibilidades en el proceso
> > > 3. a los que les genera error como `ImportError: No module named 'yaml'` se soluciona instalando
> > > 
> > > ```shell
> > > pip install pyyaml
> > > ```
> > 
> > 
> > Cual es el comando correcto a usar? porque con grade solo, omitiendo el python no funciona:
> > ![image](https://user-images.githubusercontent.com/80117497/114280109-72feaa00-99fd-11eb-8f11-9db59c9bf557.png)
> 
> `python grade`

:( sale igual 
![image](https://user-images.githubusercontent.com/80117497/114280382-9413ca80-99fe-11eb-8325-88f1ccb3eb47.png)

**Comment by calopezj** [comment]
Hola!
Hay que hacer una pequeña modificación en el archivo grade que realiza la calificación general:

![image](https://user-images.githubusercontent.com/50965626/114283964-5d47af80-9a12-11eb-8256-3665b6658997.png)

Como pueden ver en la imagen, estamos tratando de ejecutar cada grader de cada ejercicio como si fuera un programa de bash, pero en realidad es un programa de pyhon.

Pero, la modificación, en mi caso, solo funcionó al modificar dicha linea utilizando el editor de texto "nano".

Por favor prueben y me avisan.

**Comment by calopezj** [comment]
Adicional a lo que les mencioné en el comentario anterior, es importante tambien que modifiquemos las dos siguientes lineas:

![image](https://user-images.githubusercontent.com/50965626/114285008-7b64de00-9a19-11eb-90f7-caef4a984622.png)


Es decir:

Comentarear:
question_score = int(question_dir[question_dir.rfind('=')+1:-1])

y poner:

question_score = 1


y en la otra linea, comentarear:
homework_score = int(homework_dir[homework_dir.rfind('=')+1:-1])

y poner:

homework_score = 1

**Comment by gcarmonap-zz** [comment]
Hola!!!

yo hice el cambio, pero en los ejercicios de bash me seguía saliendo que no reconoce los archivos que yo generé en el ejercicio, incluso después de ejecutar el grade general con las sentencias:

sudo dos2unix grade

![image](https://user-images.githubusercontent.com/80118152/114311134-2ecde100-9ab3-11eb-9493-577cff5bada2.png)

si ejecuto el 5 (de forma individual, el grader del ejercicio 5 de bash) que es uno de los que me falla, me funcionó, lo que tuve que hacer fue ejecutar dos2unix a todos los archivos de los ejercicios bash, tanto para el grader como para el question.sh, así:

sudo dos2unix question.sh
sudo dos2unix grader

Al final en el grader general me funcionó bien :)

![image](https://user-images.githubusercontent.com/80118152/114312190-68085000-9ab7-11eb-8900-717a6ad95c07.png)


**NOTA: yo uso Windows.**
