### ISSUE TITLE
Q13 bash tuberia rota

### ISSUE THREAD

**Issue by pilarhernandez96** [jdvelasq/courses#19]
Hola, este ejercicio aun me sigue saliendo error de tubería rota, no estoy usando cut sin embargo no logro el success, si lo pruebo en el terminal sale la respuesta correcta.
![Error13](https://user-images.githubusercontent.com/80076004/114306397-882d1480-9aa1-11eb-952d-eb4c9d8fba37.PNG)

**Comment by lvasquezve** [comment]
Hay veces el comando sort también molesta cuando se hacen invocaciones desde python, puedes intentar `csvsql --query 'select city from person order by ssn' person |` y despues hacer un tratamiento a la salida.
