### ISSUE TITLE
Imagen instalada en Docker (Windows), pero usando comando de Linux

### ISSUE THREAD

**Issue by macanoso** [jdvelasq/courses#24]
Corri el comando del lenguaje de linux e intento actualizarlo al comando de windows y no me sirve

![image](https://user-images.githubusercontent.com/82194410/168383060-aa10d9d5-c431-4276-b614-99afa497f19a.png)

**Comment by lvasquezve** [comment]
Al parecer no tienes permisos, puedes abrir la consola como administrador e intentarlo nuevamente?

**Comment by macanoso** [comment]
> Al parecer no tienes permisos, puedes abrir la consola como administrador e intentarlo nuevamente?

La ejecuté como admin, si ves estoy sobre el system32 (PD: Ya la imagen la tengo, me preocupa es la ubicación)

**Comment by lvasquezve** [comment]
veo, tu pc es de 32 o 64 ?

**Comment by macanoso** [comment]
> veo, tu pc es de 32 o 64 ?

64

**Comment by lvasquezve** [comment]
Power shell, intenta desde esa terminal, Es más actualizada que la de `DOS`

**Comment by macanoso** [comment]
> Power shell, intenta desde esa terminal, Es más actualizada que la de `DOS`

Ejecutada como admin 

![image](https://user-images.githubusercontent.com/82194410/168388100-09fb3939-571d-4bf1-8eae-968bccc777b0.png)

**Comment by lvasquezve** [comment]
porfa ejecuta este comando

```bash
docker run --rm -it -v "%cd%":/workspace --name hadoop -p 8888:8888 -p 50070:50070 -p 8088:8088 jdvelasq/hadoop:2.8.5
```

**Comment by macanoso** [comment]
> porfa ejecuta este comando
> 
> ```shell
> docker run --rm -it -v "%cd%":/workspace --name hadoop -p 8888:8888 -p 50070:50070 -p 8088:8088 jdvelasq/hadoop:2.8.5
> ```

Luis perfecto! Muchas gracias

**Comment by damosorioco** [comment]
Hola! me genera el siguiente error:

![image](https://user-images.githubusercontent.com/101427484/168389195-3365ee7f-b9bd-40bb-83cc-ad25b6e36fff.png)

**Comment by lvasquezve** [comment]
Al parecer no tienes corriendo `Docker` porfa, válida bien que tengas Docker corriendo. Y los pasos de este tutorial estén realizados:
https://drive.google.com/file/d/1fVibF5ws_6umLLZtSFZKEenAw2unlF-6/view
