### ISSUE TITLE
Docker - Ports are not available: exposing port TCP 0.0.0.0:50070

### ISSUE THREAD

**Issue by hdcardon-unal** [jdvelasq/courses#26]
Error invoking remote method 'docker-start-container': Error: (HTTP code 500) server error - Ports are not available: exposing port TCP 0.0.0.0:50070 -> 0.0.0.0:0: listen tcp 0.0.0.0:50070: bind: An attempt was made to access a socket in a way forbidden by its access permissions.

**Comment by MateoSDB** [comment]
Compa, tmb me salia el error y otro compa tiro la solución en telegram. Intenta cambiando el puerto
docker run --rm -it -v "%cd%":/workspace --name hadoop -p 8888:8888 -p 25565:50070 -p 8088:8088 jdvelasq/hadoop:2.8.5
