### ISSUE TITLE
Error al ingresar nuevamente el código docker run --rm -it -v "$PWD":/workspace --name hadoop -p 8888:8888 -p 50070:50070 -p 8088:8088 jdvelasq/hadoop:2.8.5

### ISSUE THREAD

**Issue by carboledad** [jdvelasq/courses#29]
C:\Users\cearb>docker run --rm -it -v "$PWD":/workspace --name hadoop -p 8888:8888 -p 50070:50070 -p 8088:8088 jdvelasq/hadoop:2.8.5
Unable to find image 'jdvelasq/hadoop:2.8.5' locally
docker: Error response from daemon: error creating temporary lease: connection error: desc = "transport: Error while dialing dial unix /var/run/desktop-containerd/containerd.sock: connect: connection refused": unavailable.
See 'docker run --help'.

C:\Users\cearb>docker run --help

**Comment by lvasquezve** [comment]
por favor ejecuta este comando 

usuario linux
`docker run --rm -it -v "$PWD":/workspace --name hadoop -p 8888:8888 -p 25565:50070  -p 8088:8088 jdvelasq/hadoop:2.8.5`

usuarios windowas
`docker run --rm -it -v "%cd%":/workspace --name hadoop -p 8888:8888 -p 25565:50070 -p 8088:8088 jdvelasq/hadoop:2.8.5`
