### ISSUE TITLE
Permisos -> mapper.py": error=13, Permission denied - corriendo bash app.sh

### ISSUE THREAD

**Issue by MateoPG** [jdvelasq/courses#32]
Cuando estábamos realizando la sesión 4, al correr el comando bash app.sh no ejecuta y aparece el siguiente error:

`Caused by: java.io.IOException: Cannot run program "/tmp/hadoop-root/nm-local-dir/usercache/root/appcache/application_1653697434301_0003/container_1653697434301_0003_01_000012/./mapper.py": error=13, Permission denied
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at org.apache.hadoop.streaming.PipeMapRed.configure(PipeMapRed.java:208)
        ... 23 more`

¿Cómo podemos dar los permisos necesarios para que el comando ejecute sin problema?

**Comment by lvasquezve** [comment]
el error finalmente pudo ser replicado, por alguna razón no está tomando los permisos del host, para solucionarlo se propone:

`# hadoop`
`hdfs dfs -chmod 777 -R /tmp `

`# local`
`chmod 777 -R /tmp `
