### ISSUE TITLE
Dificultad Calificación LAB1

### ISSUE THREAD

**Issue by jjalgarces** [jdvelasq/courses#34]
Hola.

Al revisar la solución del LAB1 por consola, aparentemente está bien. Pero al llevarlo al GITHUB el autograding es malo y me indica el siguiente error: 

![image](https://user-images.githubusercontent.com/64942729/172063888-bcf1fe81-4052-4c27-af39-19dddcdf4311.png)

El cual no entiendo. Agradezco cualquier ayuda. @lvasquezve

**Comment by jdvelasq** [comment]
cual lab? de cual curso?
