### ISSUE TITLE
Error en autograding Laboratorio SED

### ISSUE THREAD

**Issue by EdherUnal** [jdvelasq/courses#38]
Buenas tardes,

Me podrían ayudar, por favor, con un error que se me genera en el primer laboratorio de Sed al momento de calificarlo en el autograding en GitHub. Al momento de ejecutarlo en VisualCode, el resultado es el mismo de tests.py y al probarlo con python3 tests.py, este lo califica correctamente, sin embargo, al realizar el commit y calificarse en GitHub, este lo hace erróneamente argumentando que las respuestas no coinciden (específicamente el de la fecha del 2013-06-21), cuando en realidad, probé anteriormente que sí lo hacían. Muchas gracias por su ayuda.

![Captura1](https://user-images.githubusercontent.com/101904222/173160058-9693797a-ec11-4f06-8a9f-1fcc0ab54274.PNG)
![image](https://user-images.githubusercontent.com/101904222/173160072-ba818b45-5334-4e83-be72-473400230cff.png)

**Comment by brincon1** [comment]
Lo que hice fue buscar la última ocurrencia de ";" (que en su caso sería solo la ",") y reemplazarlo por el mismo ";" seguido de \N. 
Mi código quedó: sed 's/\;$/;\\\N/' aunque de esa forma no imprime en la consola el "\N" al final de la línea pero lo califica bien cuando se sube al GitHub.

**Comment by lvasquezve** [comment]
si esta solución fue efectiva, por favor notificarlo o cerrar el issue
