### ISSUE TITLE
Problema Calificación LAB edicion-de-datos-con-sed-dlmedinan08

### ISSUE THREAD

**Issue by dlmedinan08** [jdvelasq/courses#39]
Buenas noches, al momento de elaborar la respuesta en el archivo `question.sh` para el LAB edicion-de-datos-con-sed-dlmedinan08, lo que hice fue enviar los resultados de los cambios a` data.csv` a `preprocess1.csv` y luego hacer todas las modificaciones correspondientes sobre el archivo `preprocess1.csv` como se puede ver en la imagen.
![image](https://user-images.githubusercontent.com/95106092/173479989-7e19e6ee-9031-4144-b3de-099c1ccc357b.png)

Cuando corro el` py tests.py `en mi máquina el código corre sin problemas, pero al momento de montarlo en github me calificó el punto como erróneo. 

La solución que encontré fue subir a github el archivo de `preprocess1.csv`. Esta solución es adecuada?

Quedo atenta y muchas gracias,
![image](https://user-images.githubusercontent.com/95106092/173480295-a10a7614-3af6-4310-a9d8-90d3d4a65256.png)

**Comment by lvasquezve** [comment]
Verifica la [incidencia 38](https://github.com/jdvelasq/courses/issues/38)  si este es tu mismo caso y te resuelve la inquietud, porfa

**Comment by dlmedinan08** [comment]
Buenas tardes, revié la incidencia 38, sin embargo no es mi misma situación. 

Corregí el código de otras maneras y ya me funciona. Muchas gracias.
