### ISSUE TITLE
Fila en blanco taller PIG

### ISSUE THREAD

**Issue by HectorTH1994** [jdvelasq/courses#45]
Buen día
 tengo un problema con la validación de los ejercicios de PIG, el archivo de salida se genera con una fila en blanco al final, si la imprimo en consola aparece sin esa fila en blanco, pero cuando la almaceno se genera, intente eliminarla con limit, pero no funcionó, alguien sabe cómo solucionar?
Algunos problemas los califica como correcto con esta fila en blanco y otros no.
Gracias
![image](https://user-images.githubusercontent.com/105394300/176441873-4aa91841-d2b2-4806-ae30-82a548a50d7f.png)

**Comment by lvasquezve** [comment]
El error se debe  a que no esta pudiendo encontrar la carpeta `output` por la configuración, coloca en la sentencia que almacena datos  de la siguiente manera `'output/'`
