### ISSUE TITLE
Problemas al ejecutar grader en ejercicios de python - "name 's' is no definied"

### ISSUE THREAD

**Issue by calopezj** [jdvelasq/courses#7]
Hola!

## PROBLEMA
En algunos de los ejercicios, a pesar de que la ejecución del archivo question.py es exitosa, al ejecutar el grader para evaluar el resultado se obtiene un error que indica que una de las variables no esta definida:

## EVIDENCIA - PROCEDIMIENTO
![GRader-list](https://user-images.githubusercontent.com/50965626/112723303-bc1e0c80-8edb-11eb-9e32-56d14ebe76ab.jpg)

**Comment by calopezj** [comment]
Hola! 
Esta novedad se presenta dado que existe una incompatibilidad entre una de las herramientas que usa el grader para ejecutar el código descrito en los question.sh y el uso de los list comprehensión de python. Para solucionarlo debe modificarse en el grader la linea que dice:

![image](https://user-images.githubusercontent.com/50965626/112723372-1c14b300-8edc-11eb-878f-711395cb632f.png)

Y reemplazarla por eso:

![image](https://user-images.githubusercontent.com/50965626/112723384-2f278300-8edc-11eb-9888-99a3e79797a4.png)


Sin embargo, vamos a hacer la corrección desde el repositorio para que se les actualice sin que ustedes tengan que realizar la modificación.
Les estaremos notificando para que actualicen sus repos locales.

Saludos

**Comment by lvasquezve** [comment]
es importante que si realizan esta modificación, se deben subir el grader también.

**Comment by jariasci** [comment]
Qué puedo hacer si me sigue apareciendo este error?

**Comment by lvasquezve** [comment]
Verificar el scope de tus variables en el código, ejemplo : 

```python
if 1 ==1 : 
   edad =1

print(edad)
```

Si intentas usar la variable edad, te sacara error `name 's' is no definied`  por que edad solo existe dentro del scope del `if`

Como solucionarlo

```python
edad = 0
if 1 ==1 : 
   edad =1

print(edad)
```
al inicializar  la variable, estará disponible para todo el proceso tanto en bucles, ciclos y estructuras de excepciones
