### ISSUE TITLE
Bash: Ejercicio q31

### ISSUE THREAD

**Issue by esalvarezm** [jdvelasq/courses#8]
# PROBLEMA
No se comprende que es lo que esta solicitando el ejercicio.

# EVIDENCIA
el enunciado del ejercicio q31 es:
<img width="644" alt="q31" src="https://user-images.githubusercontent.com/72627651/112725323-9f86d200-8ee5-11eb-9dce-3c0f38d4e443.png">

**Comment by lvasquezve** [comment]
El problema fue solucionada por el profesor.
